### ISSUE TITLE
TypeScript Question

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [sencha/extjs-reactor#113]
I've been having lots of trouble setting up a project with this using TypeScript.
As there are `.d.ts` files provided I'm assuming someone has got this working properly - are there any docs/boilerplate relating to doing this?

**Comment by liam-goodacre-hpe** [comment]
Based on different configuration my issues vary from: `Ext` not being defined; to things like `TextField` resolving to `undefined`, so the React component that is generated has `type: undefined` which React then complains about.

**Comment by markbrocato** [comment]
Check out https://github.com/unional/reactor-typescript-boilerplate.

The author of that project uses a typescript-specific webpack plugin (linked in the boilerplate)

Ext not being defined is generally due to:
a.) An error occurred while building ext.js.  You'll see this in the webpack output.
b.) The built ext.js file isn't being loaded in your index.html.  The boilerplates in this repo use the html-webpack-plugin to accomplish this.  If you're using something else to manage your index.html, ensure that it includes script and link tags for ext.js and ext.css.

**Comment by unional** [comment]
@markbrocato I would like to create a PR later on so that `reactor-webpack-ts-plugin` can share the same logic in `reactor-webpack-plugin` so that the two project won't diverge.

Currently `reactor-webpack-ts-plugin` and `reactor-typescript-boilerplate` is not working.

**Comment by markbrocato** [comment]
@unional Sure, send it my way.  We're working on some big updates right now but when the dust settles I may send you some PRs as well.

**Comment by liam-goodacre-hpe** [comment]
Thanks for the feedback.  Until this is ready, what I'm doing as a work-around is writing all my component rendering in `.jsx` and everything else in `.ts`.

**Comment by ak99372** [comment]
I'm also having issues using this with Typescript. Every single component comes with error about missing render at compile time. For example Grid...

`JSX element type 'Grid' is not a constructor function for JSX elements. Property 'render' is missing in type 'Grid'.	
`
I'll checkout the other repository but it would be nice if these d.ts files were compatible.

**Comment by unional** [comment]
The other two repos has been updated. You can see if it works for you. 🌷

**Comment by liam-goodacre-hpe** [comment]
This has been working fine for a while now, so I'll close this.
