### ISSUE TITLE
Live update / Hot reloading?

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#24]
I don't know if the current workflow allows it.

Also, I notice it takes a long time (11 sec in my case) for making simple changes to the code and have it reflected (manually refreshing the page right now) on the browser.
It is because the `reactor-webpack-plugin` is invoking SenchaCmd synchronously and need to wait for it to do all its stuff (that's where I get the 11 sec from, the log output from SenchaCmd).

If would be better if SenchaCmd and work outside of the toolchain and update the `ext.js` file asynchronously. Let webpack to do the change detection on both the file I'm changing and `ext.js` so that it can update the browser much faster.

Even a simple boilerplate takes 11 sec, consider in a real application it can take minutes.

**Comment by unional** [comment]
Of course, in this regards, it would be even better to pre-generate `@extjs/reactor/modern` instead of using babel to do the black magic of converting `import { Grid } from '@extjs/reactor/modern'` to `const Grid = reactify('grid')`

Would that reduce some of the workload of SenchaCmd?

**Comment by markbrocato** [comment]
Pre-generating wouldn't speed up Cmd, because it still needs to build the optimized bundle, and it would also mean that we would need to update extjs-reactor each time there is a new release of Ext JS.

The next update to extjs-reactor-webpack-plugin will only trigger a cmd rebuild when you make changes to Ext JS components.  I'm also going to include an option to rebuild with cmd asynchronously.  The downside to that is the first time you import a new Ext JS component you may refresh your browser before the cmd build is complete and the page won't load.

**Comment by markbrocato** [comment]
You can now specify `asynchronous: true` to prevent the webpack build for waiting for the sencha cmd build to finish.
