### ISSUE TITLE
webpack-plugin bugs

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#28]
Notice a few bugs when I port it over for TypeScript:

- Not handling `import { reactify as abc } from '@extjs/reactor'`
- `types[name] = xtype.toLowerCase()` will fail during `const configs = { ...types }`
- Handling `JsxSelfClosingElement`?
- Not handling `const MyGrid = reactify(SomeComponent)`

**Comment by markbrocato** [comment]
Thanks!

Will push fixes for the first two soon.  I don't think not handling JsxSelfClosingElement is an issue.  

The boilerplates use several self closing elements without issue.  If you disagree can you provide a specific case that fails?

Regarding not handling `const MyGrid = reactify(SomeComponent)`.  The webpack plugin will ensure that the Sencha Cmd build includes framework classes referenced by name.  For example: `reactify(Ext.grid.Panel)` should work once I commit the fix for point #2.  It doesn't need to do anything with user classes that are imported as modules.  Webpack will automatically include those in the main app bundle.

**Comment by markbrocato** [comment]
First two issues are fixed now in master: https://github.com/sencha/extjs-reactor/commit/1f11a7cd7620f201acc55465661ba5e28ebb780b

**Comment by unional** [comment]
> The boilerplates use several self closing elements without issue

May it be `acron` does not distinguish the two? TypeScript does thus I have to explicitly support both.
You can take a glimpse of the code [here](https://github.com/unional/extjs-reactor/tree/add-ts-boilerplate)



> Regarding not handling const MyGrid = reactify(SomeComponent)

I make sense, but I see you are handling it for `const [ Grid, Panel ] = reactify('grid', SomePanel)` case [here](https://github.com/sencha/extjs-reactor/blob/master/packages/reactor-webpack-plugin/src/extractFromJSX.js#L40)

Or do i misunderstand what it does?
