### ISSUE TITLE
How to use/include custom Ext components?

### ISSUE THREAD

**Issue by BugiDev** [sencha/extjs-reactor#33]
Hello, 
first of all great job and I am really looking forward to using this.

I have a question though, how would I use custom Ext components with this?
I have an existing Ext codebase which I would like to try and integrate with React. I have written a bunch of custom components, extending existing ones like Panel, Grid and other.

Also, is there a way to use Ext.Application, since I use a namespace for my components?
They are named like `Abc.panel.Panel` with the *xtype* of `abc-panel`.

Best regards,
Bogdan.

**Comment by markbrocato** [comment]
As long as your custom components are either included in your webpack bundle via import/require statements, or loaded via a <script> tag, you can reactify by xtype:

```javascript
import { reactify } from 'extjs-reactor';
const MyPanel = reactify('abc-panel');
```

...or by class...

```javascript
import { reactify } from 'extjs-reactor';
const MyPanel = reactify(Abc.panel.Panel);
```

I haven't tried using Ext.Application yet.  It might be possible, but probably not.  Ext.Application pretty much takes over everything, whereas this library is meant to allow you to use Ext JS as a component library rather than as an application framework.

**Comment by jmontaca** [comment]
@BugiDev were you able to get your custom component as indicated here? I'm trying to do the same thing and haven't succeeded yet.
