### ISSUE TITLE
Why Ext JS doesn't render to a root node?

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#38]
This is a generic question, but I'm sure you can my answer question since you thoroughly understand Ext JS and React.

It's a common pattern to render React apps to a root element, not to the body.  However, many Ext JS components render directly to the body element, e.g. renderTo: Ext.getBody()

See this tip: "Don’t Render to Body".

https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375#.wwg4tg55e

Why this could pose a problem for React applications and not Ext JS apps?

**Comment by markbrocato** [comment]
The points in that article are valid for Ext JS as well.  Both libraries are responsible for rendering the html inside of their respective contain elements, so inserting additional content into the container without the framework's knowledge may yield unexpected results. (One example I can think of would be the way the classic toolkit does layouts, where Ext JS needs to know the dimensions of each child element).

It's most likely that the difference, in practice, is cultural.  React is commonly used alongside other frameworks and often controls only a small part of the page.  Because of this, users may run into these sort of issues more often.  Ext JS apps, on the other hand tend to be all Ext JS.

BTW, we have a gitter channel.  Questions like these are probably more appropriately posted there:  https://gitter.im/sencha/extjs-reactor
