### ISSUE TITLE
onCloseClick property passing

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#72]
I'm just learning React and I'm not trying to be a smart guy, but I think the way the onCloseClick property is passed is not the best practice.

This is because whenever the Employee component renders, a new function is being created and passed as input.
```
...
export default class App extends Component {
    ...
    onCloseClick = () => {
        this.setState({ employee: null })
    }

    render() {
        ...
        return (
            ...
                { /* employee && <Employee employee={employee} onCloseClick={() => this.setState({ employee: null })}/> */ }
                { employee && <Employee employee={employee} onCloseClick={this.onCloseClick}/>  }
            ...
        )
    }
}
```

**Comment by markbrocato** [comment]
The problem with `onCloseClick={this.onCloseClick}` is that the this context is lost, so this.setState will be undefined and result in an error.  Instead you can do `onCloseClick={this.onCloseClick.bind(this)}`, which also results in a new function being created, which is why I like using one line arrow functions for really simple event handlers.

**Comment by AjaxSolutions** [comment]
The change that I made works though.  I don't see an error.

**Comment by markbrocato** [comment]
Ah, I misread your declaration of onCloseClick.  You're using an ES7 property initializer to bind onCloseClick to this.  I suppose you've got a point, that probably is better.  Such is life with React, best practices evolve quickly :)
